wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1668083783.928274
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 3
      - 23
      - 37
      4: 3.10.6
      5: 0.13.5
      6: 4.24.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.001
max_seq_len:
  desc: null
  value: 60
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 6
